sudo: required
services: 
  - docker

before_install:
  - docker build -t whymeoff/frontend:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true whymeoff/frontend:latest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-651765433219"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY